apiVersion: apps/v1
kind: Deployment  # Kubernetes resource kind we are creating
metadata:
  name: taskmaster-deployment
spec:
  selector:
    matchLabels:
      app: taskmaster
  replicas: 2  # Number of replicas for this deployment
  template:
    metadata:
      labels:
        app: taskmaster
    spec:
      containers:
        - name: taskmaster
          image: maryammairaj/devtaskmaster:latest  # Docker image to use for the container
          imagePullPolicy: Always  # Always pull the latest image
          ports:
            - containerPort: 8080  # The port the container exposes inside the pod

            
apiVersion: v1  # Kubernetes API version
kind: Service  # Kubernetes resource kind we are creating
metadata:
  name: taskmaster-service  # Descriptive name for the service
spec:
  selector:
    app: taskmaster  # Selector to match the app label
  ports:
    - protocol: TCP
      port: 80  # Exposes port 80 on the service
      targetPort: 8080  # Forwards traffic to port 8080 on the container
  type: LoadBalancer  # Type of service to expose the deployment externally
