name: CDPROD

on: 
  push: 
    branches: 
      - "main" 
  pull_request: 
    branches: 
      - "main" 

jobs: 
  build: 
    runs-on: self-hosted 

    steps: 
      - name: Build with Maven 
        run: mvn -B package --file pom.xml 

      - name: Login to Docker Hub 
        uses: docker/login-action@v3 
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Pull and Tag Docker Image 
        run: | 
          docker pull maryammairaj/devtaskmaster:latest 
          docker tag maryammairaj/devtaskmaster:latest maryammairaj/prodtaskmaster:latest 
          docker push maryammairaj/prodtaskmaster:latest 

      - name: Kubectl Action 
        uses: tale/kubectl-action@v1 
        with: 
          base64-kube-config: ${{ secrets.KUBE_CONFIG_PROD }} 

      - run: | 
          kubectl apply -f deployment-service.yml
